// ============================================================================
// data.js — Embedded Datasets for Password Analysis
// Contains: dictionary words, keyboard adjacency, leetspeak map
// Passwords are in data_passwords.js (auto-generated)
// ============================================================================

// ~3,500 common English words for dictionary matching and passphrase generation
export const COMMON_WORDS = new Set([
  "about", "above", "abuse", "accept", "account", "across", "action", "actual", "added",
  "adjust", "admin", "adult", "advance", "advice", "affair", "affect", "after", "again",
  "against", "agency", "agent", "agree", "ahead", "alarm", "album", "alert", "alien",
  "align", "alive", "allow", "almost", "alone", "along", "alpha", "alter", "always",
  "amaze", "among", "amount", "angel", "anger", "angle", "angry", "animal", "annual",
  "answer", "apart", "appeal", "apple", "apply", "arena", "argue", "arise", "armor",
  "army", "around", "array", "arrow", "aside", "asset", "atlas", "atom", "attach",
  "attack", "attempt", "attend", "audio", "audit", "avoid", "awake", "award", "aware",
  "awful", "bacon", "badge", "badly", "baker", "balance", "banana", "banner", "barely",
  "barrel", "barrier", "basic", "basin", "basis", "basket", "batch", "battle", "beach",
  "beast", "beauty", "become", "before", "begin", "behind", "belief", "belong", "below",
  "bench", "berry", "beyond", "bible", "birth", "bishop", "black", "blade", "blame",
  "bland", "blank", "blast", "blaze", "bleed", "blend", "bless", "blind", "block",
  "blood", "bloom", "blown", "board", "bonus", "boost", "booth", "border", "bottle",
  "bottom", "bought", "bounce", "bound", "brain", "brand", "brave", "bread", "break",
  "breed", "brick", "bride", "brief", "bring", "broad", "broke", "brown", "brush",
  "buddy", "budget", "build", "bunch", "burst", "buyer", "cabin", "cable", "candy",
  "carbon", "carry", "catch", "cause", "cedar", "chain", "chair", "chalk", "chamber",
  "chance", "change", "chaos", "chapter", "charge", "charm", "chart", "chase", "cheap",
  "check", "cheek", "cheer", "cheese", "chess", "chest", "chief", "child", "china",
  "chips", "choir", "choose", "chunk", "church", "circle", "citizen", "civil", "claim",
  "class", "clean", "clear", "clerk", "click", "cliff", "climb", "clock", "clone",
  "close", "cloth", "cloud", "coach", "coast", "color", "column", "combat", "comedy",
  "comfort", "comic", "command", "common", "company", "compare", "complex", "concept",
  "concern", "confirm", "connect", "consider", "consist", "constant", "contact",
  "contain", "content", "contest", "context", "contract", "control", "convert", "cookie",
  "copper", "corner", "correct", "cosmic", "cotton", "could", "council", "count",
  "counter", "county", "couple", "courage", "course", "court", "cousin", "cover",
  "crack", "craft", "crash", "crazy", "cream", "create", "credit", "creek", "crew",
  "crime", "crisis", "cross", "crowd", "crown", "cruel", "crush", "crystal", "curve",
  "custom", "cycle", "daddy", "daily", "dairy", "damage", "dance", "danger", "dealer",
  "death", "debate", "decent", "decide", "decline", "deeply", "defeat", "defend",
  "define", "degree", "delay", "delete", "deliver", "demand", "demon", "denial", "dense",
  "deny", "depart", "depend", "deploy", "depth", "deputy", "derive", "desert", "design",
  "desire", "detail", "detect", "device", "devote", "diamond", "differ", "digit",
  "dinner", "direct", "dirty", "disable", "discover", "dish", "dismiss", "display",
  "dispute", "distance", "district", "divide", "divine", "doctor", "dollar", "domain",
  "donate", "double", "doubt", "draft", "dragon", "drain", "drama", "dream", "dress",
  "drift", "drink", "drive", "driver", "drunk", "dying", "eager", "early", "earth",
  "eaten", "economy", "editor", "effect", "effort", "eight", "either", "elder", "elect",
  "elegant", "element", "elite", "email", "embrace", "emerge", "emission", "emotion",
  "emperor", "empire", "employ", "empty", "enable", "encounter", "encourage", "endless",
  "enemy", "energy", "enforce", "engage", "engine", "enjoy", "enormous", "enough",
  "ensure", "enter", "entire", "entry", "equal", "equip", "error", "escape", "essay",
  "estate", "eternal", "evaluate", "evening", "event", "every", "evidence", "evil",
  "evolve", "exact", "example", "exceed", "except", "excess", "exchange", "excite",
  "exclude", "execute", "exercise", "exhaust", "exhibit", "exist", "expand", "expect",
  "expense", "expert", "explain", "explore", "export", "expose", "extend", "extent",
  "extra", "extreme", "fabric", "facial", "facility", "factor", "faculty", "failed",
  "fairly", "faith", "fallen", "false", "family", "famous", "fancy", "fantasy", "farmer",
  "fashion", "father", "fault", "favor", "feature", "federal", "fellow", "female",
  "fence", "fewer", "fiber", "fiction", "field", "fifth", "fifty", "fight", "figure",
  "final", "finance", "finger", "finish", "fired", "first", "fiscal", "fixed", "flame",
  "flash", "fleet", "flesh", "flight", "float", "flood", "floor", "flour", "flower",
  "fluid", "flush", "focus", "follow", "force", "forest", "forever", "forget", "formal",
  "format", "former", "formula", "forth", "fortune", "forum", "forward", "fossil",
  "foster", "found", "fourth", "frame", "frank", "fraud", "fresh", "friend", "front",
  "frost", "fruit", "fully", "funny", "fusion", "future", "gadget", "galaxy", "garden",
  "gather", "gauge", "gender", "general", "genius", "genre", "gentle", "ghost", "giant",
  "given", "glass", "global", "glory", "golden", "gospel", "govern", "grace", "grade",
  "grain", "grand", "grant", "graph", "grasp", "grass", "grave", "great", "green",
  "greet", "grief", "grill", "gross", "ground", "group", "grove", "grown", "guard",
  "guess", "guest", "guide", "guild", "guilt", "guitar", "habit", "handle", "happy",
  "harbor", "harsh", "harvest", "haven", "headquarters", "health", "heart", "heavy",
  "hence", "hidden", "highly", "hiring", "hobby", "holder", "hollow", "honest", "honor",
  "horizon", "horror", "horse", "house", "hover", "human", "humble", "humor", "hunger",
  "hunter", "hurry", "ideal", "identity", "ignore", "illegal", "image", "imagine",
  "impact", "import", "impose", "improve", "incident", "include", "income", "increase",
  "index", "indicate", "indoor", "industrial", "infant", "inflation", "influence",
  "inform", "initial", "injury", "inner", "innocent", "input", "inquiry", "insert",
  "inside", "inspect", "install", "instance", "instead", "insure", "intact", "intend",
  "interest", "internal", "interpret", "interval", "interview", "introduce", "invade",
  "invest", "invite", "involve", "island", "isolate", "issue", "ivory", "jacket",
  "jersey", "jewel", "joint", "jolly", "journal", "journey", "judge", "juice", "jumbo",
  "junior", "justice", "justify", "kernel", "keyboard", "kidney", "kingdom", "kitchen",
  "knife", "knight", "knock", "label", "labor", "ladder", "lamp", "landscape", "laptop",
  "large", "laser", "later", "latest", "latter", "launch", "layer", "layout", "leader",
  "league", "learn", "lease", "least", "leave", "legacy", "legal", "legend", "lemon",
  "length", "lesson", "letter", "level", "lever", "liberal", "liberty", "library",
  "license", "lifetime", "light", "likely", "limit", "linear", "linger", "liquid",
  "listen", "little", "lively", "living", "lobby", "local", "locate", "logic", "lonely",
  "loose", "lottery", "lovely", "lower", "loyal", "lucky", "lunch", "luxury", "machine",
  "magical", "maiden", "mainly", "major", "maker", "manage", "manner", "mansion",
  "manual", "marble", "march", "margin", "marine", "marker", "market", "marry", "massive",
  "master", "match", "material", "matter", "mature", "mayor", "meaning", "measure",
  "media", "medium", "member", "memory", "mental", "mentor", "merchant", "mercy", "merely",
  "merit", "metal", "method", "middle", "might", "military", "million", "mineral",
  "minimum", "minor", "minute", "miracle", "mirror", "missile", "mission", "mistake",
  "mixture", "mobile", "model", "modern", "modest", "modify", "module", "moment",
  "money", "monitor", "monkey", "monster", "monthly", "moral", "moreover", "morning",
  "mortgage", "mostly", "mother", "motion", "motor", "mount", "mouse", "mouth", "movie",
  "muscle", "museum", "music", "mutual", "mystery", "narrow", "nation", "native",
  "natural", "nature", "naval", "nearby", "nearly", "needle", "negative", "neither",
  "nerve", "network", "neutral", "never", "newly", "night", "noble", "nobody", "noise",
  "nominal", "none", "normal", "notable", "nothing", "notice", "notion", "novel",
  "nuclear", "number", "nurse", "object", "observe", "obtain", "obvious", "occupy",
  "occur", "ocean", "offer", "office", "officer", "official", "often", "olive", "ongoing",
  "online", "opening", "operate", "opinion", "oppose", "option", "orange", "orbit",
  "order", "ordinary", "organic", "origin", "other", "otherwise", "ought", "outer",
  "outline", "output", "overall", "overcome", "overlook", "owner", "oxygen", "package",
  "paint", "palace", "palm", "panel", "panic", "paper", "parade", "parent", "parish",
  "parking", "partly", "partner", "party", "passage", "passion", "passive", "patch",
  "patient", "pattern", "pause", "peace", "penalty", "people", "pepper", "percent",
  "perfect", "perform", "period", "permit", "person", "phrase", "piano", "pilot",
  "pioneer", "pitch", "pixel", "place", "plain", "planet", "plant", "plate", "platform",
  "player", "plaza", "please", "pledge", "plenty", "pocket", "poetry", "point", "poison",
  "police", "policy", "polish", "polite", "political", "pollution", "popular", "portal",
  "portion", "portrait", "position", "positive", "possess", "possible", "postal",
  "potato", "potential", "pottery", "pound", "poverty", "powder", "power", "praise",
  "prayer", "precise", "predict", "prefer", "premium", "prepare", "present", "preserve",
  "president", "press", "assume", "pressure", "pretty", "prevent", "previous", "price",
  "pride", "priest", "primary", "prince", "princess", "principal", "print", "prior",
  "prison", "privacy", "private", "prize", "probe", "problem", "proceed", "process",
  "produce", "product", "profile", "profit", "program", "project", "promise", "promote",
  "prompt", "proof", "proper", "property", "proposal", "propose", "prospect", "protect",
  "protein", "protest", "proud", "prove", "provide", "province", "public", "publish",
  "pulse", "punch", "puppet", "purchase", "purple", "purpose", "pursue", "puzzle",
  "qualify", "quality", "quarter", "queen", "quest", "question", "quick", "quiet",
  "rabbit", "racial", "radar", "radical", "radio", "raise", "range", "rapid", "rarely",
  "rather", "ratio", "reach", "react", "reader", "ready", "reality", "realize", "really",
  "reason", "rebel", "recall", "receive", "recent", "recipe", "recognize", "recommend",
  "record", "recover", "reduce", "refer", "reflect", "reform", "refuse", "regard",
  "regime", "region", "register", "regret", "regular", "reject", "relate", "release",
  "relief", "religion", "rely", "remain", "remark", "remedy", "remember", "remind",
  "remote", "remove", "render", "renew", "rental", "repair", "repeat", "replace",
  "report", "request", "require", "rescue", "research", "reserve", "resign", "resist",
  "resolve", "resort", "resource", "respond", "restore", "result", "retail", "retain",
  "retire", "retreat", "return", "reveal", "revenue", "reverse", "review", "revolt",
  "reward", "rhythm", "rider", "rifle", "right", "rigid", "rival", "river", "robot",
  "rocket", "romantic", "rotate", "rough", "round", "route", "royal", "rugby", "ruler",
  "rural", "sacred", "sacrifice", "safety", "saint", "salary", "salmon", "sample",
  "satellite", "satisfy", "sauce", "saving", "scale", "scandal", "scene", "schedule",
  "scheme", "scholar", "school", "science", "scope", "score", "screen", "script",
  "search", "season", "second", "secret", "sector", "secure", "segment", "select",
  "seller", "senate", "senior", "sense", "sentence", "separate", "sequence", "series",
  "serious", "servant", "serve", "service", "session", "settle", "seven", "severe",
  "shadow", "shall", "shame", "shape", "share", "sharp", "shell", "shelter", "shift",
  "shine", "shirt", "shock", "shoot", "shore", "short", "should", "shower", "sight",
  "signal", "silence", "silly", "silver", "similar", "simple", "since", "single",
  "sister", "situated", "sixth", "sixty", "skill", "sleep", "slice", "slight", "slope",
  "smart", "smell", "smile", "smoke", "smooth", "snake", "soccer", "social", "society",
  "software", "solar", "soldier", "solid", "solution", "solve", "someone", "sorry",
  "source", "south", "space", "spare", "speak", "special", "specific", "speech", "speed",
  "spend", "sphere", "spirit", "split", "sport", "spray", "spread", "spring", "square",
  "stable", "staff", "stage", "stake", "stand", "standard", "start", "state", "status",
  "steady", "steam", "steel", "steep", "stick", "still", "stock", "stone", "store",
  "storm", "story", "straight", "strange", "strategy", "stream", "street", "strength",
  "stress", "stretch", "strict", "strike", "strip", "stroke", "strong", "struggle",
  "studio", "study", "stuff", "style", "subject", "submit", "substance", "succeed",
  "sudden", "suffer", "sugar", "suggest", "summer", "summit", "super", "supply",
  "support", "suppose", "surface", "surgery", "surplus", "surprise", "survey",
  "survive", "suspect", "suspend", "sustain", "swallow", "swear", "sweet", "swift",
  "swing", "switch", "symbol", "system", "table", "tackle", "talent", "target", "taste",
  "teach", "temple", "tenant", "tender", "tennis", "tension", "terror", "thank",
  "theme", "theory", "therapy", "thing", "think", "third", "thirty", "thorough",
  "those", "thought", "threat", "three", "throat", "throw", "thumb", "ticket", "tiger",
  "tight", "timber", "tissue", "title", "today", "together", "tomorrow", "tongue",
  "tonight", "topic", "total", "totally", "touch", "tough", "tower", "trace", "track",
  "trade", "tradition", "traffic", "train", "trait", "transfer", "transform", "transit",
  "translate", "travel", "treasure", "treat", "treaty", "trend", "trial", "tribe",
  "trick", "trigger", "triple", "triumph", "troop", "trophy", "trouble", "truck",
  "truly", "trust", "truth", "tunnel", "twelve", "twenty", "twice", "twist", "typical",
  "ugly", "ultimate", "unable", "uncle", "undergo", "understand", "union", "unique",
  "united", "unity", "universe", "unknown", "unless", "unlike", "unlikely", "until",
  "unusual", "update", "upper", "upset", "urban", "value", "variety", "various",
  "vehicle", "venture", "verify", "version", "vessel", "veteran", "victim", "video",
  "viewer", "village", "violate", "virtue", "virus", "visible", "vision", "visit",
  "visual", "vital", "voice", "volume", "volunteer", "voyage", "wage", "waiting",
  "wander", "warfare", "warm", "warning", "waste", "watch", "water", "wealth", "weapon",
  "weather", "weigh", "welcome", "welfare", "western", "whatever", "wheat", "wheel",
  "whenever", "wherever", "whisper", "white", "whole", "widely", "widow", "width",
  "willing", "window", "winter", "wisdom", "withdraw", "within", "without", "witness",
  "woman", "wonder", "wooden", "worker", "world", "worry", "worship", "worst", "worth",
  "would", "wound", "writer", "wrong", "yield", "young", "youth", "zero", "zombie"
]);

// Words as an array for passphrase generation (random access needed)
export const WORD_LIST = Array.from(COMMON_WORDS);

// QWERTY keyboard adjacency graph for spatial pattern detection
export const KEYBOARD_ADJACENCY = {
  '1': ['2', 'q', 'w'],
  '2': ['1', '3', 'q', 'w', 'e'],
  '3': ['2', '4', 'w', 'e', 'r'],
  '4': ['3', '5', 'e', 'r', 't'],
  '5': ['4', '6', 'r', 't', 'y'],
  '6': ['5', '7', 't', 'y', 'u'],
  '7': ['6', '8', 'y', 'u', 'i'],
  '8': ['7', '9', 'u', 'i', 'o'],
  '9': ['8', '0', 'i', 'o', 'p'],
  '0': ['9', 'o', 'p', '-'],
  '-': ['0', 'p', '=', '['],
  '=': ['-', '[', ']'],
  'q': ['1', '2', 'w', 'a', 's'],
  'w': ['1', '2', '3', 'q', 'e', 'a', 's', 'd'],
  'e': ['2', '3', '4', 'w', 'r', 's', 'd', 'f'],
  'r': ['3', '4', '5', 'e', 't', 'd', 'f', 'g'],
  't': ['4', '5', '6', 'r', 'y', 'f', 'g', 'h'],
  'y': ['5', '6', '7', 't', 'u', 'g', 'h', 'j'],
  'u': ['6', '7', '8', 'y', 'i', 'h', 'j', 'k'],
  'i': ['7', '8', '9', 'u', 'o', 'j', 'k', 'l'],
  'o': ['8', '9', '0', 'i', 'p', 'k', 'l', ';'],
  'p': ['9', '0', '-', 'o', '[', 'l', ';', '\''],
  '[': ['-', '=', 'p', ']', ';', '\''],
  ']': ['=', '[', '\'', '\\'],
  'a': ['q', 'w', 's', 'z', 'x'],
  's': ['q', 'w', 'e', 'a', 'd', 'z', 'x', 'c'],
  'd': ['w', 'e', 'r', 's', 'f', 'x', 'c', 'v'],
  'f': ['e', 'r', 't', 'd', 'g', 'c', 'v', 'b'],
  'g': ['r', 't', 'y', 'f', 'h', 'v', 'b', 'n'],
  'h': ['t', 'y', 'u', 'g', 'j', 'b', 'n', 'm'],
  'j': ['y', 'u', 'i', 'h', 'k', 'n', 'm', ','],
  'k': ['u', 'i', 'o', 'j', 'l', 'm', ',', '.'],
  'l': ['i', 'o', 'p', 'k', ';', ',', '.', '/'],
  ';': ['o', 'p', '[', 'l', '\'', '.', '/'],
  '\'': ['p', '[', ']', ';', '/'],
  'z': ['a', 's', 'x'],
  'x': ['a', 's', 'd', 'z', 'c'],
  'c': ['s', 'd', 'f', 'x', 'v'],
  'v': ['d', 'f', 'g', 'c', 'b'],
  'b': ['f', 'g', 'h', 'v', 'n'],
  'n': ['g', 'h', 'j', 'b', 'm'],
  'm': ['h', 'j', 'k', 'n', ','],
  ',': ['j', 'k', 'l', 'm', '.'],
  '.': ['k', 'l', ';', ',', '/'],
  '/': ['l', ';', '\'', '.']
};

// Leetspeak substitution map (leet → original)
export const LEET_MAP = {
  '0': 'o',
  '1': 'il',
  '2': 'z',
  '3': 'e',
  '4': 'a',
  '5': 's',
  '6': 'g',
  '7': 't',
  '8': 'b',
  '9': 'g',
  '@': 'a',
  '!': 'i',
  '$': 's',
  '+': 't',
  '(': 'c',
  '|': 'il',
  '<': 'c',
  '{': 'c',
  '^': 'a'
};

// Common sequences for pattern detection
export const SEQUENCES = {
  lower: 'abcdefghijklmnopqrstuvwxyz',
  upper: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  digits: '0123456789',
  common: [
    'qwertyuiop', 'asdfghjkl', 'zxcvbnm',
    'qwerty', 'asdfgh', 'zxcvbn',
    'qwer', 'asdf', 'zxcv',
    'qaz', 'wsx', 'edc', 'rfv', 'tgb', 'yhn', 'ujm'
  ]
};
